config/routes.rb
Rails.application.routes.draw do
  # get 'doses/new'
  # get 'doses/create'
  # get 'doses/update'
  # get 'doses/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true


end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :ingredient, uniqueness: { scope: :cocktail_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktails_params)
    @cocktail.save
    redirect_to cocktails_path
  end

  def edit
    @cocktail = Cocktail.find(cocktails_params)
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    redirect_to cocktails_path
  end

  def destroy
  end

  def cocktails_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      render :new
    end
  end


  def destroy
    @dose = Dose.find(params[:id])
    cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktail_helper.rb
module CocktailHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <div class="form-group">
  <%= f.input :name %>
</div>
<%= f.button :submit %>
<% end %>

app/views/cocktails/create.html.erb
<h1>Cocktail#create</h1>
<p>Find me in app/views/cocktail/create.html.erb</p>

app/views/cocktails/destroy.html.erb
<h1>Cocktail#destroy</h1>
<p>Find me in app/views/cocktail/destroy.html.erb</p>

app/views/cocktails/edit.html.erb
<h1>Add A Description To Your Cocktail</h1>
<p></p>

app/views/cocktails/index.html.erb
<body>
<div class="banner">
  <h1>All Cocktails</h1>
<button type="button" class="btn btn-outline-danger text-decoration-none"><%= link_to 'Make Your Own', new_cocktail_path %></button>
  </div>
  <div class="cards">
  <% @cocktails.each do |cocktail| %>
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(http://kitt.lewagon.com/placeholder/cities/rio)">
  <h3><%= link_to cocktail.name, cocktail_path(cocktail) %></h3>
  </div>
  <% end %>
  </div>
</body>

app/views/cocktails/new.html.erb
<h1>Create Your Own Cocktail!</h1>

<%=  simple_form_for [@cocktail] do |f| %>
<%= f.input :name  %>
<%= f.submit 'Start Blending...' %>
<% end %>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<body>
<div class='container'>
<h1><%= @cocktail.name%></h1>
<%= link_to "Add dose", doses_path %>
<h3>Ingredients:</h3>
<% @cocktail.doses.each do |dose|%>
<p><%= dose.description%></p><strong><%= dose.ingredient.name %></strong>
<button type="button" class="btn btn-outline-danger text-decoration-none"><%= link_to "delete", cocktail_dose_path(@cocktail,dose), method: :delete %></button>
<% end %>
<button type="button" class="btn btn-outline-success text-decoration-none"><%= link_to "Add An Ingredient", new_cocktail_dose_path(@cocktail)%></button>
<button type="button" class="btn btn-outline-warning text-decoration-none"><%= link_to 'All Cocktails', cocktails_path %></button>
</div>
</body>

app/views/cocktails/update.html.erb
<h1>Cocktail#update</h1>
<p>Find me in app/views/cocktail/update.html.erb</p>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<h1>What's Tasty?</h1>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <div class="form-group">
  <%= f.input :description, required: true %>
  <%= f.association :ingredient, required: true %>
</div>


<%= f.button :submit %>
<% end %>

app/views/doses/update.html.erb
<h1>Doses#update</h1>
<p>Find me in app/views/doses/update.html.erb</p>

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>